services:
  - type: web
    name: yvi-soft-email-server
    runtime: node
    buildCommand: npm install && cd backend && npm install
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: PORT
        value: "3001"