services:
  - type: web
    name: yvi-soft-email-server
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: PORT
        value: "3001"
      - key: FRONTEND_URL
        value: "https://yvi-soft-solutions.onrender.com"