services:
  - type: web
    name: yvi-soft-email-server
    runtime: node
    buildCommand: npm run build
    startCommand: node start.js
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: PORT
        value: "3001"